// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using LifeOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LifeOSDbContext))]
    [Migration("20260916061038_Jalon5WeekScenarios")]
    partial class Jalon5WeekScenarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.Domain.Articles.GroceryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.ComposedMeals.ComposedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("composed_meals", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.ComposedMeals.ComposedMealPart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComposedMealId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityFactor")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComposedMealId");

                    b.HasIndex("RecipeId");

                    b.ToTable("composed_meal_parts", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.FoodItems.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("IsCorrectionOf")
                        .HasColumnType("uuid")
                        .HasColumnName("is_correction_of");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("OffBarcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("off_barcode");

                    b.Property<string>("OffPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("off_payload");

                    b.Property<string>("ReferenceUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_unit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("idx_food_items_household_id");

                    b.HasIndex("HouseholdId", "OffBarcode")
                        .HasDatabaseName("idx_food_items_household_off_barcode");

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Households.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Households.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SupabaseUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Households.MemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PortionCoefficient")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Households.UserConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyBaseEnergyKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetCarbsG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TargetFatsG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TargetNetDeficitKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TargetProteinG")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("user_configurations", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.ActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedEnergyKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayPlanId");

                    b.ToTable("activity_sessions", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.DayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BikeCommute")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WeekId");

                    b.ToTable("day_plans", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.PlannedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComposedMealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DayPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComposedMealId");

                    b.HasIndex("DayPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("planned_meals", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.PlannedMealPart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlannedMealId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PortionMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberProfileId");

                    b.HasIndex("PlannedMealId");

                    b.ToTable("planned_meal_parts", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.Week", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdId", "StartsOn");

                    b.ToTable("weeks", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.WeekScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Applied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Explanation")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RankingObjective")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.HasIndex("WeekId", "RankingObjective");

                    b.ToTable("week_scenarios", (string)null);
                });

            modelBuilder.Entity("LifeOS.Domain.Articles.GroceryItem", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LifeOS.Domain.Articles.GroceryPriceEntry", "PriceHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ArticleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("ObservedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ArticleId");

                            b1.ToTable("article_price_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleId");
                        });

                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("LifeOS.Domain.ComposedMeals.ComposedMeal", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.ComposedMeals.ComposedMealPart", b =>
                {
                    b.HasOne("LifeOS.Domain.ComposedMeals.ComposedMeal", null)
                        .WithMany("Parts")
                        .HasForeignKey("ComposedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.FoodItems.FoodItem", b =>
                {
                    b.OwnsOne("LifeOS.Domain.FoodItems.Nutrition", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("FoodItemId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("CaloriesPerUnit")
                                .HasColumnType("double precision")
                                .HasColumnName("calories_per_unit");

                            b1.Property<double?>("CarbsPerUnit")
                                .HasColumnType("double precision")
                                .HasColumnName("carbs_per_unit");

                            b1.Property<double?>("FatsPerUnit")
                                .HasColumnType("double precision")
                                .HasColumnName("fats_per_unit");

                            b1.Property<double?>("ProteinsPerUnit")
                                .HasColumnType("double precision")
                                .HasColumnName("proteins_per_unit");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("food_items");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("LifeOS.Domain.Households.HouseholdMember", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Households.MemberProfile", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany("MemberProfiles")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Households.UserConfiguration", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Recipes.Recipe", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("LifeOS.Domain.Articles.GroceryItem", null)
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Recipes.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.Stores.Store", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.ActivitySession", b =>
                {
                    b.HasOne("LifeOS.Domain.WeekPlanning.DayPlan", null)
                        .WithMany()
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.DayPlan", b =>
                {
                    b.HasOne("LifeOS.Domain.WeekPlanning.Week", null)
                        .WithMany("DayPlans")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.PlannedMeal", b =>
                {
                    b.HasOne("LifeOS.Domain.ComposedMeals.ComposedMeal", null)
                        .WithMany()
                        .HasForeignKey("ComposedMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeOS.Domain.WeekPlanning.DayPlan", null)
                        .WithMany("PlannedMeals")
                        .HasForeignKey("DayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.PlannedMealPart", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.MemberProfile", null)
                        .WithMany()
                        .HasForeignKey("MemberProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeOS.Domain.WeekPlanning.PlannedMeal", null)
                        .WithMany("Parts")
                        .HasForeignKey("PlannedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.Week", b =>
                {
                    b.HasOne("LifeOS.Domain.Households.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.WeekScenario", b =>
                {
                    b.HasOne("LifeOS.Domain.WeekPlanning.Week", null)
                        .WithMany("Scenarios")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeOS.Domain.ComposedMeals.ComposedMeal", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("LifeOS.Domain.Households.Household", b =>
                {
                    b.Navigation("MemberProfiles");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("LifeOS.Domain.Recipes.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.DayPlan", b =>
                {
                    b.Navigation("PlannedMeals");
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.PlannedMeal", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("LifeOS.Domain.WeekPlanning.Week", b =>
                {
                    b.Navigation("DayPlans");

                    b.Navigation("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
